add missing <array> include
This fixes the following warning in trex_astf_dp_core.cpp:
  error: variable ‘std::array<CTcpPerThreadCtx*, 2> ctxs’ has initializer but incomplete type
  std::array<CTcpPerThreadCtx*,2> ctxs{ m_flow_gen->m_c_tcp, m_flow_gen->m_s_tcp };
                                  ^~~~

Signed-off-by: Gabriel Ganne <gabriel.ganne@gmail.com>